export * from "./utils.js";
export * from "./apply.js";
export const identifier = (value) => Object.freeze({ kind: "identifier", value });
export const constant = (value, datatype) => Object.freeze({ kind: "constant", value, datatype });
export const dereference = (key) => Object.freeze({ kind: "dereference", key });
export const projection = (key) => Object.freeze({ kind: "projection", key });
export const injection = (key) => Object.freeze({ kind: "injection", key });
export const tuple = (slots) => Object.freeze({ kind: "tuple", slots: Object.freeze(slots) });
export const match = (cases) => Object.freeze({ kind: "match", cases: Object.freeze(cases) });
export const map = (source, value) => Object.freeze({ kind: "map", source, value });
export const mapping = (maps) => Object.freeze(maps);
